import { Brygada_1918 } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/footer'

const sans = Brygada_1918({ 
  
  subsets: ['latin'] })

export const metadata = {
  title: 'KIKI NEX',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}